import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  
  return (
    <div>
      {children}
    </div>
        
  );
}


/* export default function AuthLayout ({ children }: {
    children: React.ReactNode;
}){
    return (
        <main className="flex justify-center">
            <div className="w-full sm:w-87.5 px-10">
                { children }
            </div>
            
        </main>
    ); 
} */