import type { Metadata } from "next";
import Sidebar from "../../components/admin/main/sidebar";
//import { Geist, Geist_Mono } from "next/font/google";






export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <div className="flex">
        <div className="flex">
            <Sidebar />
            {children}
        </div>
    </div>
  );
}