import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";


import { Navbar } from "../components/main/Navbar";
import { NavbarAdmin } from "../components/main/NavbarAdmin";
import { Footer } from "../components/main/Footer";
import { FiltroProvider } from "@/src/context/FilterContext";


/* const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
}); */

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <div>
      <FiltroProvider>
        <Navbar />
        <NavbarAdmin />
          {children}
        <Footer />
      </FiltroProvider>
    </div>
  );
}
